# criando evento
POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "new event",
    "details": null,
    "maximumAttendees": 1
}

###

# gerando erro de validação
POST http://localhost:3333/events
Content-Type: application/json

{
    "title": 123,
    "details": null,
    "maximumAttendees": 1
}

###

# criando attendee em um evento
POST http://localhost:3333/events/acf48139-99ea-41db-b262-f4108092f0c9/attendee
Content-Type: application/json

{
    "name": "hong",
    "email": "hong@hong.com"
}

###

GET http://localhost:3333/events/95a82a95-8c4f-4fa4-b8ab-24f4fa8e2119

###

# url de check-in e outras informações do attendee
GET http://localhost:3333/attendee/3/badge

###

# attendee check-in
GET http://localhost:3333/attendee/5/check-in

###

#pesquisando attendees em um evento
GET http://localhost:3333/events/2f64d431-ad7c-4844-912f-2248e4947bb1/attendees?query=hong
